import io
import numpy as np
import soundfile as sf
from kokoro import KPipeline

_pipeline = None


def _get_pipeline():
    global _pipeline
    if _pipeline is None:
        import torch
        device = "cuda" if torch.cuda.is_available() else "cpu"
        _pipeline = KPipeline(lang_code="a", device=device)
    return _pipeline


async def generate_tts(text: str) -> bytes:
    """Generate TTS audio from text using Kokoro."""
    pipeline = _get_pipeline()
    generator = pipeline(text, voice="af_heart")

    all_audio = []
    for _, _, audio in generator:
        import torch
        if isinstance(audio, torch.Tensor):
            audio = audio.cpu().numpy()
        all_audio.append(audio)

    combined = np.concatenate(all_audio)

    buf = io.BytesIO()
    sf.write(buf, combined, 24000, format="WAV")
    buf.seek(0)
    return buf.read()


def make_wav_header(sample_rate: int = 24000, num_channels: int = 1, bits_per_sample: int = 16) -> bytes:
    header = bytearray(44)
    header[0:4] = b'RIFF'
    file_size = 0x7FFFFFFF
    header[4:8] = file_size.to_bytes(4, 'little')
    header[8:12] = b'WAVE'
    header[12:16] = b'fmt '
    header[16:20] = (16).to_bytes(4, 'little')
    header[20:22] = (1).to_bytes(2, 'little')
    header[22:24] = num_channels.to_bytes(2, 'little')
    header[24:28] = sample_rate.to_bytes(4, 'little')
    byte_rate = sample_rate * num_channels * (bits_per_sample // 8)
    header[28:32] = byte_rate.to_bytes(4, 'little')
    block_align = num_channels * (bits_per_sample // 8)
    header[32:34] = block_align.to_bytes(2, 'little')
    header[34:36] = bits_per_sample.to_bytes(2, 'little')
    header[36:40] = b'data'
    data_size = 0x7FFFF000
    header[40:44] = data_size.to_bytes(4, 'little')
    return bytes(header)


async def stream_tts(text: str):
    """Yield raw 16-bit PCM audio chunks as they are generated by Kokoro."""
    pipeline = _get_pipeline()
    generator = pipeline(text, voice="af_heart")
    for _, _, audio in generator:
        import torch
        if isinstance(audio, torch.Tensor):
            audio = audio.cpu().numpy()
        pcm_data = (audio * 32767).astype(np.int16).tobytes()
        yield pcm_data
