import io
import os
import numpy as np
import soundfile as sf
from kokoro import KPipeline

_pipeline = None

CACHE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "cache")
os.makedirs(CACHE_DIR, exist_ok=True)


def get_cache_path(session_id: int) -> str:
    return os.path.join(CACHE_DIR, f"session_{session_id}.wav")


def _get_pipeline():
    global _pipeline  # ponytail: lazy singleton, avoids import-time GPU check
    if _pipeline is None:
        import torch  # ponytail: lazy import, GPU detection at first use only
        device = "cuda" if torch.cuda.is_available() else "cpu"
        _pipeline = KPipeline(lang_code="a", device=device)
    return _pipeline


async def generate_tts(text: str) -> bytes:
    """Generate TTS audio from text using Kokoro."""
    pipeline = _get_pipeline()
    generator = pipeline(text, voice="af_heart")

    all_audio = []
    for _, _, audio in generator:
        import torch  # ponytail: lazy import for Tensor→ndarray conversion
        arr = audio.cpu().numpy() if isinstance(audio, torch.Tensor) else audio
        all_audio.append(arr)

    combined = np.concatenate(all_audio)

    buf = io.BytesIO()
    sf.write(buf, combined, 24000, format="WAV")
    buf.seek(0)
    return buf.read()


async def generate_voice_timings(text: str) -> tuple[bytes, list[dict]]:
    """Generate TTS WAV bytes and exact word timings using Kokoro sample counts."""
    pipeline = _get_pipeline()
    generator = pipeline(text, voice="af_heart")

    all_audio = []
    word_timings = []
    current_time = 0.0

    for gs, _, audio in generator:
        import torch  # ponytail: lazy import for Tensor→ndarray conversion
        arr = audio.cpu().numpy() if isinstance(audio, torch.Tensor) else audio
        all_audio.append(arr)

        # Calculate exact duration in seconds for this chunk
        chunk_duration = len(arr) / 24000.0

        # Extract words from the grapheme string
        words = [w for w in gs.split() if w.strip()]
        if words:
            word_duration = chunk_duration / len(words)
            for i, w in enumerate(words):
                word_timings.append({
                    "word": w,
                    "start": current_time + (i * word_duration),
                    "end": current_time + ((i + 1) * word_duration)
                })

        current_time += chunk_duration

    combined = np.concatenate(all_audio)

    buf = io.BytesIO()
    sf.write(buf, combined, 24000, format="WAV")
    buf.seek(0)
    wav_bytes = buf.read()

    return wav_bytes, word_timings


def make_wav_header(sample_rate: int = 24000, num_channels: int = 1, bits_per_sample: int = 16) -> bytes:
    header = bytearray(44)
    header[0:4] = b'RIFF'
    file_size = 0x7FFFFFFF
    header[4:8] = file_size.to_bytes(4, 'little')
    header[8:12] = b'WAVE'
    header[12:16] = b'fmt '
    header[16:20] = (16).to_bytes(4, 'little')
    header[20:22] = (1).to_bytes(2, 'little')
    header[22:24] = num_channels.to_bytes(2, 'little')
    header[24:28] = sample_rate.to_bytes(4, 'little')
    byte_rate = sample_rate * num_channels * (bits_per_sample // 8)
    header[28:32] = byte_rate.to_bytes(4, 'little')
    block_align = num_channels * (bits_per_sample // 8)
    header[32:34] = block_align.to_bytes(2, 'little')
    header[34:36] = bits_per_sample.to_bytes(2, 'little')
    header[36:40] = b'data'
    data_size = 0x7FFFF000
    header[40:44] = data_size.to_bytes(4, 'little')
    return bytes(header)


async def stream_tts(text: str):
    """Yield raw 16-bit PCM audio chunks as they are generated by Kokoro."""
    pipeline = _get_pipeline()
    generator = pipeline(text, voice="af_heart")
    for _, _, audio in generator:
        import torch  # ponytail: lazy import for Tensor→ndarray conversion
        arr = audio.cpu().numpy() if isinstance(audio, torch.Tensor) else audio
        pcm_data = (arr * 32767).astype(np.int16).tobytes()
        yield pcm_data
