"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { motion } from "motion/react";
import { bounce } from "@/lib/animations";
import { Persona } from "@/components/ai-elements/persona";
import type { PersonaState } from "@/components/ai-elements/persona";
import { sendVoiceMessage } from "@/lib/api";
import type { WordTiming } from "@/lib/api";
import { ProgressiveBlur } from "@/components/ui/skiper-ui/skiper41";

interface VoiceModeProps {
  sessionId: number;
  notes: string;
  onClose: () => void;
  onNoteChange?: () => void;
}

export function VoiceMode({ sessionId, notes, onClose, onNoteChange }: VoiceModeProps) {
  const [personaState, setPersonaState] = useState<PersonaState>("idle");
  const [transcript, setTranscript] = useState("");
  const [aiSubtitle, setAiSubtitle] = useState("");
  const [wordTimings, setWordTimings] = useState<WordTiming[]>([]);
  const [audioCurrentTime, setAudioCurrentTime] = useState(0);
  const [audioDuration, setAudioDuration] = useState(0);

  const recognitionRef = useRef<any>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const audioUrlRef = useRef<string | null>(null);
  const transcriptRef = useRef("");
  const abortRef = useRef<AbortController | null>(null);
  const audioCtxRef = useRef<AudioContext | null>(null);
  const subtitleRef = useRef<HTMLDivElement>(null);
  const [subtitleScrollOpacity, setSubtitleScrollOpacity] = useState(0);
  const [subtitleBottomOpacity, setSubtitleBottomOpacity] = useState(0);
  const [isDesktop, setIsDesktop] = useState(false);

  useEffect(() => {
    setIsDesktop(window.matchMedia("(hover: hover) and (pointer: fine)").matches);
  }, []);

  // Get or create a shared AudioContext (unlocked on user gesture)
  const getAudioCtx = useCallback(() => {
    if (!audioCtxRef.current || audioCtxRef.current.state === "closed") {
      audioCtxRef.current = new AudioContext();
    }
    return audioCtxRef.current;
  }, []);

  // Unlock audio on user gesture — play a silent buffer so future play() calls succeed
  const unlockAudio = useCallback(() => {
    const ctx = getAudioCtx();
    if (ctx.state === "suspended") {
      ctx.resume().catch(() => {});
    }
    // Play a tiny silent buffer to fully unlock the context
    const buf = ctx.createBuffer(1, 1, 22050);
    const src = ctx.createBufferSource();
    src.buffer = buf;
    src.connect(ctx.destination);
    src.start();
  }, [getAudioCtx]);

  const killAudio = useCallback(() => {
    if (audioRef.current) {
      // Null handlers BEFORE clearing source — otherwise setting src="" and
      // calling load() fires onerror, which triggers the Web Audio fallback
      // and re-plays the same audio (the "repeating" bug on interrupt).
      const el = audioRef.current as any;
      if (el.onended !== undefined) el.onended = null;
      if (el.onerror !== undefined) el.onerror = null;
      if (el.ontimeupdate !== undefined) el.ontimeupdate = null;
      if (el.onloadedmetadata !== undefined) el.onloadedmetadata = null;
      audioRef.current.pause();
      audioRef.current.src = "";
      audioRef.current.load();
      audioRef.current = null;
    }
    if (audioUrlRef.current) {
      URL.revokeObjectURL(audioUrlRef.current);
      audioUrlRef.current = null;
    }
    setAudioCurrentTime(0);
    setAudioDuration(0);
  }, []);

  const stopAll = useCallback(() => {
    recognitionRef.current?.stop();
    recognitionRef.current = null;
    killAudio();
    abortRef.current?.abort();
    abortRef.current = null;
    setAiSubtitle("");
    setWordTimings([]);
  }, [killAudio]);

  const speakResponse = useCallback(async (question: string) => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    try {
      setPersonaState("thinking");
      killAudio();
      setAiSubtitle("");
      setWordTimings([]);

      // 1. Fetch LLM response first to get subtitle text & save chat messages
      const { response: responseText, word_timings, note_changes, canvas_changes } = await sendVoiceMessage(sessionId, question);
      if (controller.signal.aborted) return;

      console.log("[voice] got response, word_timings:", word_timings.length);
      setAiSubtitle(responseText);
      setWordTimings(word_timings);

      // Notify parent if notes or canvases were changed
      if (note_changes?.length || canvas_changes?.length) {
        onNoteChange?.();
      }

      // 2. Play cached TTS audio (already generated by voice-chat POST)
      const url = `/api/sessions/${sessionId}/tts`;
      console.log("[voice] playing audio from:", url);
      const audio = new Audio(url);
      audioRef.current = audio;

      audio.onplaying = () => {
        if (!controller.signal.aborted) {
          setPersonaState("speaking");
        }
      };

      audio.ontimeupdate = () => {
        if (!controller.signal.aborted) {
          setAudioCurrentTime(audio.currentTime);
        }
      };

      audio.onloadedmetadata = () => {
        if (!controller.signal.aborted) {
          setAudioDuration(audio.duration || 0);
        }
      };

      audio.onended = () => {
        killAudio();
        setPersonaState("idle");
      };

      audio.onerror = (e) => {
        console.error("[voice] audio error:", e);
        killAudio();
        setPersonaState("idle");
      };

      await audio.play();
      console.log("[voice] audio.play() succeeded");
    } catch (err: any) {
      console.error("[voice] speakResponse failed:", err?.name, err?.message);
      if (err.name !== "AbortError") {
        setAiSubtitle("Sorry, something went wrong. Please try again.");
        setPersonaState("idle");
      }
    }
  }, [sessionId, killAudio, onNoteChange]);

  const startListening = useCallback(() => {
    if (personaState === "speaking" || personaState === "thinking") {
      stopAll();
    }
    setTranscript("");
    setAiSubtitle("");
    setWordTimings([]);

    // Unlock audio on the user gesture so playback later succeeds
    unlockAudio();

    const SpeechRecognition =
      (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) return;

    const recognition = new SpeechRecognition();
    recognition.continuous = false;
    recognition.interimResults = true;
    recognition.lang = "en-US";

    recognition.onstart = () => {
      setPersonaState("listening");
      setTranscript("");
      transcriptRef.current = "";
    };

    recognition.onresult = (event: any) => {
      const result = Array.from(event.results)
        .map((r: any) => r[0].transcript)
        .join("");
      setTranscript(result);
      transcriptRef.current = result;
    };

    recognition.onend = () => {
      const q = transcriptRef.current.trim();
      if (q) {
        speakResponse(q);
      } else {
        setPersonaState("idle");
      }
    };

    recognition.onerror = () => {
      setPersonaState("idle");
    };

    recognitionRef.current = recognition;
    recognition.start();
  }, [personaState, stopAll, speakResponse, unlockAudio]);

  const stopListening = useCallback(() => {
    recognitionRef.current?.stop();
  }, []);

  const handleDown = useCallback(() => {
    startListening();
  }, [startListening]);

  const handleUp = useCallback(() => {
    stopListening();
  }, [stopListening]);

  useEffect(() => {
    return () => {
      stopAll();
      audioCtxRef.current?.close().catch(() => {});
    };
  }, [stopAll]);

  // Spacebar push-to-talk on PC
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.code === "Space" && !e.repeat && document.activeElement?.tagName !== "INPUT") {
        e.preventDefault();
        startListening();
      }
    };
    const handleKeyUp = (e: KeyboardEvent) => {
      if (e.code === "Space" && document.activeElement?.tagName !== "INPUT") {
        e.preventDefault();
        stopListening();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  }, [startListening, stopListening]);

  // Auto-scroll to latest spoken word
  useEffect(() => {
    if (!subtitleRef.current) return;
    const container = subtitleRef.current;
    const words = container.querySelectorAll("span");
    for (let i = words.length - 1; i >= 0; i--) {
      const span = words[i];
      if (!span.classList.contains("opacity-0")) {
        const containerRect = container.getBoundingClientRect();
        const spanRect = span.getBoundingClientRect();
        const offset = spanRect.top - containerRect.top + container.scrollTop - containerRect.height / 2 + spanRect.height / 2;
        container.scrollTo({ top: Math.max(0, offset), behavior: "smooth" });
        break;
      }
    }
  }, [audioCurrentTime]);

  const handleSubtitleScroll = useCallback(() => {
    if (!subtitleRef.current) return;
    const { scrollTop, scrollHeight, clientHeight } = subtitleRef.current;
    const maxScroll = scrollHeight - clientHeight;
    setSubtitleScrollOpacity(maxScroll > 0 ? Math.min(1, scrollTop / 100) : 0);
    setSubtitleBottomOpacity(maxScroll > 0 ? Math.min(1, (maxScroll - scrollTop) / 100) : 0);
  }, []);

  return (
    <div className="flex flex-col h-full w-full relative">
      <div className={`absolute top-3 z-10 ${isDesktop ? "left-1/2 -translate-x-1/2" : "left-3"}`}>
        <motion.button
          onClick={(e) => { e.stopPropagation(); stopAll(); onClose(); }}
          whileTap={{ scale: 0.9 }}
          transition={bounce}
          className="px-4 py-2 rounded-full bg-red-500 text-white text-sm font-medium hover:bg-red-600 transition-colors cursor-pointer"
        >
          Close
        </motion.button>
      </div>

      <div className="flex-1 flex flex-col items-center justify-center select-none">
        <div
          className="flex items-center justify-center cursor-pointer"
          onMouseDown={handleDown}
          onMouseUp={handleUp}
          onMouseLeave={handleUp}
          onTouchStart={handleDown}
          onTouchEnd={handleUp}
        >
          <Persona variant="halo" state={personaState} className="size-64" forceColor={[0, 0, 0]} />
        </div>

        <div className="pb-16 flex flex-col items-center gap-4 w-full max-w-md">
          {transcript && (
            <div className="text-sm text-muted-foreground text-center px-4 italic">
              "{transcript}"
            </div>
          )}

          {wordTimings.length > 0 && (
            <div className="relative overflow-hidden max-w-lg w-full">
              <div ref={subtitleRef} onScroll={handleSubtitleScroll} className="bg-transparent border-none shadow-none text-center px-6 max-h-[240px] overflow-y-auto leading-relaxed antialiased tracking-wide text-lg md:text-xl font-medium transition-all duration-300">
                {wordTimings.map((item, idx) => {
                  const isSpoken = personaState === "idle" || audioCurrentTime >= item.start;
                  return (
                    <span
                      key={idx}
                      className={`inline-block transition-all duration-500 ease-out mr-1.5 ${
                        isSpoken
                          ? "text-slate-800 opacity-100 translate-y-0 scale-100 font-medium"
                          : "opacity-0 translate-y-2 scale-95 pointer-events-none"
                      }`}
                    >
                      {item.word}
                    </span>
                  );
                })}
              </div>
              <div style={{ opacity: subtitleScrollOpacity }} className="pointer-events-none transition-opacity duration-150">
                <ProgressiveBlur position="top" backgroundColor="#f0f0f0" height="100px" blurAmount="6px" />
              </div>
              <div style={{ opacity: subtitleBottomOpacity }} className="pointer-events-none transition-opacity duration-150">
                <ProgressiveBlur position="bottom" backgroundColor="#f0f0f0" height="100px" blurAmount="6px" />
              </div>
            </div>
          )}

          <p className="text-xs text-muted-foreground">
            {personaState === "listening"
              ? "Listening... release to send"
              : personaState === "thinking"
                ? "Thinking..."
                : personaState === "speaking"
                  ? "Speaking... hold to interrupt"
                  : isDesktop ? "Hold Spacebar to speak" : "Hold to speak"}
          </p>
        </div>
      </div>
    </div>
  );
}
